stages:
  - deploy

deploy_job:
  stage: deploy
  tags:
    - linux
  only:
    - main
  script:
    - sudo -u alexey git -C /home/alexey/projects/onmychat fetch --all
    - sudo -u alexey git -C /home/alexey/projects/onmychat checkout main
    - sudo -u alexey git -C /home/alexey/projects/onmychat pull
    - sudo systemctl restart onmychat

upgrade_job:
  stage: deploy
  tags:
    - linux
  when: manual
  script:
    - echo "$SUDO_PASSWORD" | sudo -S -u alexey bash -c "cd /home/alexey/projects/onmychat && if [ ! -d venv ]; then python3 -m venv venv; fi"
    - echo "$SUDO_PASSWORD" | sudo -S -u alexey bash -c "source /home/alexey/projects/onmychat/venv/bin/activate && pip install -r /home/alexey/projects/onmychat/requirements.txt && playwright install"
    - sudo systemctl restart onmychat
