stages:
  - deploy

deploy_job:
  stage: deploy
  tags:
    - linux
  only:
    - main
  script:
    - sudo -u alexey git -C /home/alexey/projects/onmychat fetch --all
    - sudo -u alexey git -C /home/alexey/projects/onmychat checkout $CI_COMMIT_SHA
    - sudo systemctl restart onmychat
