[settings]
# System prompt for initial LLM behavior
DEFAULT_SYSTEM_PROMPT_FILE = default.txt
DEFAULT_ASSISTANT_NAME = June
DEFAULT_ASSISTANT_TITLE = Junior assistant

# Telegram bot token
TELEGRAM_BOT_TOKEN = your_bot_token_here

# OLLAMA URL
OLLAMA_URL = http://localhost:11434

# LLM defaults
DEFAULT_MODEL = gemma3:12b
NSFW_MODEL = do_your_reasearch_bro
SFW_MODEL = gemma3:12b
DEFAULT_API_KEY = sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DEFAULT_KB_ID = your_default_kb_id_here
STORAGE_ROOT = /path/to/root

# ComfyUI integration
COMFY_API_URL = http://localhost:8188
WORKFLOW_GENERAL_PATH = flow.json
WORKFLOW_CHARACTER_PATH = character_flow.json
COMFY_OUTPUT_DIR = /path/to/ComfyUI/output
COMFY_INPUT_DIR = /path/to/ComfyUI/input
AVATAR_DIR = user_avatars

REALISTIC_MODEL = juggernautXL_ragnarokBy.safetensors
REALISTIC_MODEL_NSFW = doyourresearch.safetensors
DREAM_MODEL = realDream_sdxlPony19.safetensors
DREAM_MODEL_NSFW = doyourresearch.safetensors
TOONED_MODEL = novaillustrousNSFW_v20.safetensors
TOONED_MODEL_NSFW = doyourresearch.safetensors